# Generated by Django 6.0 on 2025-12-08 14:35

from decouple import config
from django.db import migrations


def create_schema(apps, schema_editor):
    """
    Create PostgreSQL schema if it doesn't exist.
    This allows multiple Django projects to share the same database.
    """
    db_schema = config("DB_SCHEMA", default="test")
    if db_schema and schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            # Create schema if it doesn't exist
            cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{db_schema}";')


def drop_schema(apps, schema_editor):
    """
    Drop PostgreSQL schema (reverse migration).
    WARNING: This will drop all tables in the schema!
    """
    db_schema = config("DB_SCHEMA", default="test")
    if db_schema and schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'DROP SCHEMA IF EXISTS "{db_schema}" CASCADE;')


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_schema, reverse_code=drop_schema),
    ]
